# Generated by Django 4.0.1 on 2022-01-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Question',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='paper.question')),
            ],
            options={
                'verbose_name': 'Question Answer Choice',
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer_choices',
            field=models.ManyToManyField(blank=True, related_name='+', to='paper.QuestionAnswerChoice'),
        ),
        migrations.CreateModel(
            name='PaperQuestionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='paper.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='paper.QuestionAnswerChoice')),
            ],
            options={
                'verbose_name': 'Paper Question Item',
                'ordering': ('sequence', 'id'),
            },
        ),
    ]
