# Generated by Django 4.0.1 on 2022-01-15 16:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='questionanswerchoice',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
